# Generated by Django 4.0.1 on 2022-01-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact',
            new_name='phone',
        ),
    ]
